server:
  port: 6789
spring:
  application:
    name: eureka-movie
  servlet:
    multipart:
      enabled: true #默认true,允许上传文件
      max-file-size: 50MB  #每一个文件的大小
      max-request-size: 1024MB #总大小

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #修改html文件以后，刷新页面可更新，默认值为true
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      #defaultZone: http://Mary:4321@host1:8761/eureka/,http://Mary:4321@host2:8762/eureka/,http://Mary:4321@host3:8763/eureka/
      defaultZone: http://Jack:1234@localhost:8761/eureka
logging:
  level:
    root: INFO
    
